#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install -y haproxy=2.6.\*
# enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
config="\nfrontend birukt.tech-https\n\tbind *:80\n\tmode http\n\tdefault_backend birukt.tech-backend\n\nbackend birukt.tech-backend\n\tbalance roundrobin\n\toption forwardfor\n\tserver 31344-web-01 54.84.11.137:80 check\n\tserver 31344-web-02 100.25.145.199:80 check\n\n"
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
